server:
  port: 8080

spring:
  datasource:
    username: root
    password: 111
    url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  # MyBatis-Plus 配置项，配置通用的 Mapper 和分页插件等
  global-config:
    db-config:
      id-type: auto  # 配置主键自增策略

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.itedus.lottery.rpc
